function generate_protocol

% Variables
pCa_values = [4.5, 6.1, 6.2, 6.4, 9.0];

for i=1:numel(pCa_values)

    % Create the file string for the protocol
    protocol_file_string = sprintf('sim_input/%.0f/horslen_ramp_protocol_%.0f.txt', ...
    [10 10]*pCa_values(i));

    % Make the directory if required
    path_string = fileparts(fullfile(cd, protocol_file_string));
    if (~isdir(path_string))
    mkdir(path_string);
    end
    
    
% Generate the protocol
generate_triangle_protocol( ...
    'output_file_string', protocol_file_string, ...
    'pre_first_triangle_s',0.85, ...
    'plateau_s',[0 .2], ...
    'pre_ktr_s',0, ...
    'activating_pCa', pCa_values(i), ...
    'no_of_triangles', 2, ...
    'inter_triangle_s', 0.001, ...
    'triangle_rise_time_s',0.0843, ...
    'triangle_nm',50, ...
    'pre_Ca_s', 0);
end