function generate_protocol

% Variables
protocol_file_string = 'horslen_ramp_protocol.txt';

% Generate the protocol
generate_triangle_protocol( ...
    'output_file_string', protocol_file_string, ...
    'pre_first_triangle_s',0.85, ...
    'plateau_s',[0 .2], ...
    'pre_ktr_s',0, ...
    'activating_pCa', 4.5, ...
    'no_of_triangles', 2, ...
    'inter_triangle_s', 0.001, ...
    'triangle_rise_time_s',0.0843, ...
    'triangle_nm',50, ...
    'pre_Ca_s', 0);